apiVersion: apps/v1
kind: Deployment
metadata:
  name: raasbridge-validator
spec:
  replicas: 5
  selector:
    matchLabels:
      app: raasbridge-validator
  template:
    metadata:
      labels:
        app: raasbridge-validator
    spec:
      containers:
        - name: raas-validator
          image: raasystem/raasbridge-validator:latest
          ports:
            - containerPort: 8545
            - containerPort: 30303
          resources:
            requests:
              cpu: "1"
              memory: "2Gi"
            limits:
              cpu: "4"
              memory: "8Gi"
